#ifndef I_DEFAULTS_H
#define I_DEFAULTS_H

#define I_DISPLAY_HEATMAP_DEFAULT EINA_TRUE
#define I_DISPLAY_SEARCH_DEFAULT EINA_TRUE
#define I_DISPLAY_PATH_DEFAULT EINA_TRUE
#define I_DISPLAY_HEIGHT_DEFAULT EINA_TRUE

#define I_SIM_TRAVELERS_DEFAULT 20

#define I_WORLD_HEIGHT_MULT_MIN 1
#define I_WORLD_HEIGHT_MULT_MAX INT_MAX
#define I_WORLD_HEIGHT_MULT_STEP 1
#define I_WORLD_HEIGHT_MULT_DEFAULT 1

#define I_WORLD_GEN_W_MIN 32
#define I_WORLD_GEN_W_MAX 2048
#define I_WORLD_GEN_W_STEP 32
#define I_WORLD_GEN_W_DEFAULT 128

#define I_WORLD_GEN_H_MIN 32
#define I_WORLD_GEN_H_MAX 2048
#define I_WORLD_GEN_H_STEP 32
#define I_WORLD_GEN_H_DEFAULT 128

#define I_WORLD_GEN_DENSITY_MIN 1
#define I_WORLD_GEN_DENSITY_MAX 1024
#define I_WORLD_GEN_DENSITY_STEP 1
#define I_WORLD_GEN_DENSITY_DEFAULT 16

#define I_PATH_SEARCH_ITER_MAX_DEFAULT 1000
#define I_PATH_SEARCH_ITER_SPEED_DEFAULT 0.001
#define I_PATH_SEARCH_DIAGONAL_DEFAULT EINA_TRUE
#define I_PATH_WALK_STRENGTH_DEFAULT 0.5
#define I_PATH_WALK_DEGRADE_DEFAULT 16
#define I_PATH_WALK_DEGRADE_INT_DEFAULT 10

#define I_PATH_INF_DIST_MANHAT_DEFAULT 0.5
#define I_PATH_INF_DIST_DIAGON_DEFAULT 0.5
#define I_PATH_INF_DIST_EUCLID_DEFAULT 0.5
#define I_PATH_INF_DESASC_DEFAULT 0.5
#define I_PATH_INF_PATH_DEFAULT 0.5

#endif /*I_DEFAULTS_H*/
